from Service.model.chatbot import chatbot
from Service.common.data.transcription_context import transcription_context

async def subject_identification_processing() ->str:
    """
    Process subject identification by interacting with a chatbot model.

    This asynchronous function retrieves the current transcription context,
    sends it to a chatbot for processing, and returns the generated response.
    The chatbot can be used to identify or provide information related to
    the transcription context.

    Returns:
        str: The response generated by the chatbot based on the transcription context.
    """
    context = transcription_context.transcription
    response_text = chatbot(context, conversation_identifier = True)
    return response_text.response